### ISSUE TITLE
Unexpected error : Looking for a placeholder but found [*ENDIF*] in message!

### ISSUE THREAD

**Issue by pdemaret** [arnoldle/phplist-plugin-conditionalPlaceholderPlugin#1]
Hello, I ran into this problem when using the plugin with an `[*ELSEIF*]` clause as described on the plugin web page:

Clause that fails with the error "Looking for a placeholder but found `[*ENDIF*]` in message!" when arriving at the last step (Finish) of the phplist campaign.
`[*IF*][*~HF(M.)*]Cher[*ELSEIF*][*~HF(Mme)*]Chère[*ELSEIF*]Bonjour[*ENDIF*]`
Clause that succeeds:
`[*IF*][*~HF(M.)*]Cher[*ELSEIF*][*~HF(Mme)*]Chère[*ENDIF*]`
In this case, there is no text if the attribute HF is not defined.

What is really strange is that I can use the first clause with success when using the testing functionality of phplist (i.e. sending a test message to check the result).

Software version:
phplist 3.2.4
conditionalPlaceholder Plugin version 2.0a9

Please let me know if you need something else, or... what I am during wrong.

Thank you for this plugin,
Patrick.

**Comment by arnoldle** [comment]
Hi,

The answer is very simple. The last [_ELSEIF_] should not be an “ELSEIF,” because there is no test in the final clause. Instead of what you have, you should write the following”

```
[*IF*][*~HF(M.)*]Cher[*ELSEIF*][*~HF(Mme)*]Chère[*ELSE*]Bonjour[*ENDIF*]
```

That should fix the problem. Notice that in the expression that works, you have  only the one [_ELSEIF_], which is correctly followed by a test.

The meaning of the error message is as follows:

```
After the second [*ELSEIF*], the plugin expects to find a test. But there is no test there, so that the next symbol found is [*ENDIF*] instead of the expected test.
```

I hope that helps.

Arnold

**Comment by pdemaret** [comment]
Thank you very much for this clear explanation. Dumb on my part not to notice the ending `[*ELSE*]` and not `[*ELSEIF*]`.

And thank you again for this great plugin.

Patrick.
